### ISSUE TITLE
Error when using the plugin for a long time

### ISSUE THREAD

**Issue by SnonSS** [reosfire/TemporaryWhiteList#4] opened 2022-11-02 12:59 UTC
THIS ERROR OCCURRS WHEN THE PLUGIN WORKS FOR A LONG TIME I ADDED MYSELF FOR A TIME AND THIS ERROR APPEARS AND I KILL ME FROM THE SERVER AND CAN'T LOGIN I NEED TO RESTART THE SERVER AND THEN IT WILL WORK YOU CAN FIX IT SOMEONE:

[13:14:50 ERROR]: PID: 22 | Suspended: false | Native: false | State: TIMED_WAITING
[13:14:50 ERROR]: java.base@17.0.2/jdk.internal.misc.Unsafe.park(Native Method)
[13:14:50 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.shaded.com.zaxxer.hikari.util.ConcurrentBag.borrow(ConcurrentBag.java:151)
[13:14:50 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.shaded.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:180)
[13:14:50 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.shaded.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
[13:14:50 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.shaded.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
[13:14:50 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.temporarywhitelist.data.providers.SqlDataProvider.get(SqlDataProvider.java:96)
[13:14:50 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.temporarywhitelist.data.PlayerDatabase.tryRefreshPlayer(PlayerDatabase.java:171)
[13:14:50 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.temporarywhitelist.data.PlayerDatabase.getPlayerData(PlayerDatabase.java:37)
[13:14:50 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.temporarywhitelist.data.PlayerDatabase.canJoin(PlayerDatabase.java:66)
[13:14:50 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.temporarywhitelist.TemporaryWhiteList.lambda$runKickerTask$4(TemporaryWhiteList.java:219)
[13:14:50 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.temporarywhitelist.TemporaryWhiteList$$Lambda$5567/0x0000000801c98a30.run(Unknown Source)
[13:14:50 ERROR]: java.base@17.0.2/java.lang.Thread.run(Thread.java:833)
[13:14:55 ERROR]: PID: 22 | Suspended: false | Native: false | State: TIMED_WAITING
[13:14:55 ERROR]: java.base@17.0.2/jdk.internal.misc.Unsafe.park(Native Method)
[13:14:55 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.shaded.com.zaxxer.hikari.util.ConcurrentBag.borrow(ConcurrentBag.java:151)
[13:14:55 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.shaded.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:180)
[13:14:55 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.shaded.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
[13:14:55 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.shaded.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
[13:14:55 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.temporarywhitelist.data.providers.SqlDataProvider.get(SqlDataProvider.java:96)
[13:14:55 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.temporarywhitelist.data.PlayerDatabase.tryRefreshPlayer(PlayerDatabase.java:171)
[13:14:55 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.temporarywhitelist.data.PlayerDatabase.getPlayerData(PlayerDatabase.java:37)
[13:14:55 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.temporarywhitelist.data.PlayerDatabase.canJoin(PlayerDatabase.java:66)
[13:14:55 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.temporarywhitelist.TemporaryWhiteList.lambda$runKickerTask$4(TemporaryWhiteList.java:219)
[13:14:55 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.temporarywhitelist.TemporaryWhiteList$$Lambda$5567/0x0000000801c98a30.run(Unknown Source)
[13:14:55 ERROR]: java.base@17.0.2/java.lang.Thread.run(Thread.java:833)
[13:15:00 ERROR]: PID: 22 | Suspended: false | Native: false | State: TIMED_WAITING
[13:15:00 ERROR]: java.base@17.0.2/jdk.internal.misc.Unsafe.park(Native Method)
[13:15:00 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.shaded.com.zaxxer.hikari.util.ConcurrentBag.borrow(ConcurrentBag.java:151)
[13:15:00 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.shaded.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:180)
[13:15:00 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.shaded.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
[13:15:00 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.shaded.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
[13:15:00 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.temporarywhitelist.data.providers.SqlDataProvider.get(SqlDataProvider.java:96)
[13:15:00 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.temporarywhitelist.data.PlayerDatabase.tryRefreshPlayer(PlayerDatabase.java:171)
[13:15:00 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.temporarywhitelist.data.PlayerDatabase.getPlayerData(PlayerDatabase.java:37)
[13:15:00 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.temporarywhitelist.data.PlayerDatabase.canJoin(PlayerDatabase.java:66)
[13:15:00 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.temporarywhitelist.TemporaryWhiteList.lambda$runKickerTask$4(TemporaryWhiteList.java:219)
[13:15:00 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.temporarywhitelist.TemporaryWhiteList$$Lambda$5567/0x0000000801c98a30.run(Unknown Source)
[13:15:00 ERROR]: java.base@17.0.2/java.lang.Thread.run(Thread.java:833)
[13:15:05 ERROR]: PID: 22 | Suspended: false | Native: false | State: TIMED_WAITING
[13:15:05 ERROR]: java.base@17.0.2/jdk.internal.misc.Unsafe.park(Native Method)
[13:15:05 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.shaded.com.zaxxer.hikari.util.ConcurrentBag.borrow(ConcurrentBag.java:151)
[13:15:05 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.shaded.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:180)
[13:15:05 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.shaded.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
[13:15:05 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.shaded.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
[13:15:05 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.temporarywhitelist.data.providers.SqlDataProvider.get(SqlDataProvider.java:96)
[13:15:05 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.temporarywhitelist.data.PlayerDatabase.tryRefreshPlayer(PlayerDatabase.java:171)
[13:15:05 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.temporarywhitelist.data.PlayerDatabase.getPlayerData(PlayerDatabase.java:37)
[13:15:05 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.temporarywhitelist.data.PlayerDatabase.canJoin(PlayerDatabase.java:66)
[13:15:05 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.temporarywhitelist.TemporaryWhiteList.lambda$runKickerTask$4(TemporaryWhiteList.java:219)
[13:15:05 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.temporarywhitelist.TemporaryWhiteList$$Lambda$5567/0x0000000801c98a30.run(Unknown Source)
[13:15:05 ERROR]: java.base@17.0.2/java.lang.Thread.run(Thread.java:833)
[13:15:10 ERROR]: PID: 22 | Suspended: false | Native: false | State: TIMED_WAITING
[13:15:10 ERROR]: java.base@17.0.2/jdk.internal.misc.Unsafe.park(Native Method)
[13:15:10 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.shaded.com.zaxxer.hikari.util.ConcurrentBag.borrow(ConcurrentBag.java:151)
[13:15:10 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.shaded.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:180)
[13:15:10 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.shaded.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
[13:15:10 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.shaded.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
[13:15:10 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.temporarywhitelist.data.providers.SqlDataProvider.get(SqlDataProvider.java:96)
[13:15:10 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.temporarywhitelist.data.PlayerDatabase.tryRefreshPlayer(PlayerDatabase.java:171)
[13:15:10 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.temporarywhitelist.data.PlayerDatabase.getPlayerData(PlayerDatabase.java:37)
[13:15:10 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.temporarywhitelist.data.PlayerDatabase.canJoin(PlayerDatabase.java:66)
[13:15:10 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.temporarywhitelist.TemporaryWhiteList.lambda$runKickerTask$4(TemporaryWhiteList.java:219)
[13:15:10 ERROR]: TemporaryWhiteList-2.3.jar//ru.reosfire.temporarywhitelist.TemporaryWhiteList$$Lambda$5567/0x0000000801c98a30.run(Unknown Source)
[13:15:10 ERROR]: java.base@17.0.2/java.lang.Thread.run(Thread.java:833)

AND ERROR WHEN ENABLING THE PLUGIN ITSELF:

[16:00:53 INFO]: [TWL] Enabling TemporaryWhiteList v2.3
[16:00:53 INFO]: [TWL] Loading configurations...
[16:00:53 INFO]: [TWL] Loading messages...
[16:00:53 INFO]: [TWL] Loading data...
[16:00:53 ERROR]: [TWL] [STDERR] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[16:00:53 WARN]: Nag author(s): '[reosfire]' of 'TemporaryWhiteList' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[16:00:53 ERROR]: [TWL] [STDERR] SLF4J: Defaulting to no-operation (NOP) logger implementation
[16:00:53 ERROR]: [TWL] [STDERR] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[16:00:54 INFO]: [TWL] Loading commands...
[16:00:54 INFO]: [TWL] Loading placeholders...
[16:00:54 INFO]: [PlaceholderAPI] Successfully registered expansion: twl [2.3]
[16:00:54 INFO]: [TWL] Loading events handler...
[16:00:54 INFO]: [TWL] Enabling...
[16:00:54 INFO]: [TWL] Loaded

**Comment by HarvelsX** [comment] 2022-11-03 11:26
@reosfire 
PLEASE! Close the streams of reading query results (ResultSet), as well as the connection! 
Example of using `try-close`: https://github.com/HarvelsX/TemporaryWhiteList/blob/master/src/main/java/ru/reosfire/temporarywhitelist/Data/SqlDataProvider.java#L82

**Comment by reosfire** [comment] 2022-11-03 19:14
@SnonSS 
Can you test this build: [TWLTest.zip](https://github.com/reosfire/TemporaryWhiteList/files/9932303/TWLTest.zip), please. Because I can't reproduce this error on my pc

**Comment by HarvelsX** [comment] 2022-11-03 22:08
@reosfire
> https://github.com/reosfire/TemporaryWhiteList/commit/4274b5611e5df1af10baffcca6b9515a2da5c1b1

It remains to do the same with `.getConnection()`

**Comment by DeriksonTM** [comment] 2023-03-20 19:27
@HarvelsX Have you waited or solved the problem? Maybe you use another plugin?

**Comment by AloneRUS** [comment] 2023-03-21 06:38
> @HarvelsX Have you waited or solved the problem? Maybe you use another plugin?

WhitelistByTime looks better. It also has issues, but the author is accepting my pull requests and we've solved a lot of problems.

**Comment by reosfire** [comment] 2023-03-28 17:38
> @HarvelsX Have you waited or solved the problem? Maybe you use another plugin?

As you can see I tried to solve this issue and gave a build that could fix that issue but get ignored by author of this issue request. So if you still interested in this plugin you can try to download latest build from spigot with this fixes.

**Comment by reosfire** [comment] 2023-03-28 17:40
> > @HarvelsX Have you waited or solved the problem? Maybe you use another plugin?
> 
> WhitelistByTime looks better. It also has issues, but the author is accepting my pull requests and we've solved a lot of problems.

This is very interesting how you appeared out of nowhere with an advertisement for this plugin but oh well :)

**Comment by HarvelsX** [comment] 2023-03-29 10:25
@DeriksonTM, probably solved in the last commits. 
If there are problems, it is not difficult to create another issue.
@reosfire, please close it.

**Closed as completed** 2023-03-29 18:54 UTC

**Comment by AloneRUS** [comment] 2023-03-31 10:53
> > > @HarvelsX Have you waited or solved the problem? Maybe you use another plugin?
> > 
> > 
> > WhitelistByTime looks better. It also has issues, but the author is accepting my pull requests and we've solved a lot of problems.
> 
> This is very interesting how you appeared out of nowhere with an advertisement for this plugin but oh well :)

Just a quick help for this guy. I had the same problem with your plugin because I'm here
